<a href="https://colab.research.google.com/github/SanjitaPrajapati/AI4CCEE_Fall_2024/blob/main/ssanjita__lecture3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: connect to google drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!mkdir act_2

In [ ]:
!ls

act_2  sample_data

In [ ]:
!echo > act_2/file1.txt

In [ ]:
%cd act_2

/content/act_2

In [ ]:
# prompt: how to create shell script

%%bash
#!/bin/bash

# This is a shell script

ls -l

# You can add more commands here

total 4
-rw-r--r-- 1 root root 1 Sep 11 22:48 file1.txt

In [ ]:
!echo "#!/bin/bash" > script.sh

In [ ]:
!echo "echo hello world" >> script.sh

In [ ]:
!echo "ls -l" >> script.sh

In [ ]:
#Activity #2 : Intro to python

name = "Sanjita"
age = "25"
print("Hello my name is ",name," and I am ",age," years old")

string1 = "Hello my name is "+name+" and I am "+age+" years old"
print(string1.upper())
print(string1.lower())

hobby = "painting"
string2 = "I am "+age+" years old! I love "+hobby
str2 = string1.replace("I am"+age+"years old","I love "+hobby)
print(str2)

Hello my name is  Sanjita  and I am  25  years old
HELLO MY NAME IS SANJITA AND I AM 25 YEARS OLD
hello my name is sanjita and i am 25 years old
Hello my name is Sanjita and I am 25 years old

In [ ]:
asphalt_unit_cost = 0
asphalt_quantity=0
concrete_unit_cost = 0
concrete_quantity = 0
labor_unit_cost = 0
labor_hours = 0

In [ ]:
asphalt_unit_cost = input('Enter asphalt_unit_cost: ')
asphalt_quantity=input('Enter asphalt_quantity: ')
concrete_unit_cost = input('Enter concrete_unit_cost: ')
concrete_quantity = input('Enter concrete_quantity: ')
labor_unit_cost = input('Enter labor_unit_cost: ')
labor_hours = input('Enter labor_hours: ')

Enter asphalt_unit_cost: 10
Enter asphalt_quantity: 20
Enter concrete_unit_cost: 10
Enter concrete_quantity: 20
Enter labor_unit_cost: 10
Enter labor_hours: 20

In [ ]:
asphalt_total_cost = int(asphalt_unit_cost)*int(asphalt_quantity)
concrete_total_cost = int(concrete_unit_cost)*int(concrete_quantity)
labor_total_cost = int(labor_unit_cost)*int(labor_hours)
total_cost = asphalt_total_cost+concrete_total_cost+labor_total_cost
print(asphalt_total_cost)
print(concrete_total_cost)
print(labor_total_cost)
print(total_cost)

threshhold = 50000
if total_cost<50000:
  print("Project is under budget")
else:
  print("Project is over budget")

200
200
200
600
Project is under budget

In [ ]:
! pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/example.csv')

In [ ]:
# Displaying the first few rows
print(df.head())
# Displaying summary statistics
print(df.describe())
# Checking data types and missing values
print(df.info())

    Name  Age         City  Gender
0   John   26     New York    Male
1   Jane   31  Los Angeles  Female
2  Alice   22      Chicago  Female
3    Bob   45      Houston    Male
4  Carol   37      Phoenix  Female
             Age
count  55.000000
mean   31.127273
std     6.675146
min    21.000000
25%    26.000000
50%    29.000000
75%    35.500000
max    46.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    55 non-null     object
 1   Age     55 non-null     int64
 2   City    55 non-null     object
 3   Gender  55 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.8+ KB
None

In [ ]:
# Selecting a single column
ages = df['Age']
# Selecting multiple columns
subset = df[['Name', 'City']]
# Filtering based on a condition
young_people = df[df['Age'] < 30]

In [ ]:
# # Adding a new column
# df['Gender'] = ['Male', 'Female', 'Male']
# # Modifying values
# df.loc[df['Name'] == 'John', 'Age'] = 26

In [ ]:
!pip install matplotlib

Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.7)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/235-Nov.csv')

In [ ]:
df.head()

,owner-id,network-id,date,time,utc-offset,start-ime,end-time,detector-id,status,lane-id,...,small-class-count,medium-class-count,large-class-count,device-id,link-direction,detector-type,sample-period,device-description,month,day
0,Q-Free,Q-Free,20211110,80900,0,80800,80900,DMDS20-WB EN,OK,1,...,0,0,0,OpenTMS-Detector46573-0,w,unknown,60,ON_RAMP,11,10
1,Q-Free,Q-Free,20211110,80900,0,80800,80900,DMDS20-WB RL,OK,4,...,0,1,0,OpenTMS-Detector46573-1,w,unknown,60,NORMAL,11,10
2,Q-Free,Q-Free,20211110,80900,0,80800,80900,DMDS20-WB RCL,OK,3,...,0,0,0,OpenTMS-Detector46573-2,w,unknown,60,NORMAL,11,10
3,Q-Free,Q-Free,20211110,80900,0,80800,80900,DMDS20-WB LCL,OK,2,...,0,0,0,OpenTMS-Detector46573-3,w,unknown,60,NORMAL,11,10
4,Q-Free,Q-Free,20211110,80900,0,80800,80900,DMDS20-WB LL,OK,1,...,0,0,0,OpenTMS-Detector46573-4,w,unknown,60,NORMAL,11,10

In [ ]:
df.isnull().sum()

owner-id              0
network-id            0
date                  0
time                  0
utc-offset            0
start-ime             0
end-time              0
detector-id           0
status                0
lane-id               0
lane-count            0
lane-occupancy        0
lane-speed            0
small-class-count     0
medium-class-count    0
large-class-count     0
device-id             0
link-direction        0
detector-type         0
sample-period         0
device-description    0
month                 0
day                   0
dtype: int64

In [ ]:
df.describe()

,date,time,utc-offset,start-ime,end-time,lane-id,lane-count,lane-occupancy,lane-speed,small-class-count,medium-class-count,large-class-count,sample-period,month,day
count,1.287800e+05,128780.000000,128780.0,128780.000000,128780.000000,128780.000000,128780.000000,128780.000000,128780.000000,128780.000000,128780.000000,128780.000000,128780.0,128780.0,128780.000000
mean,2.021111e+07,117912.004193,0.0,117932.395558,117912.004193,2.200000,9.634074,3.797197,61.164964,0.203960,7.616548,1.581472,60.0,11.0,6.665942
std,3.440028e+00,69021.866649,0.0,69021.150108,69021.866649,1.166195,8.714397,4.332574,6.787330,0.648766,6.935575,2.237594,0.0,0.0,3.396851
min,2.021110e+07,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,60.0,11.0,2.000000
25%,2.021110e+07,60100.000000,0.0,60100.000000,60100.000000,1.000000,2.000000,0.000000,58.000000,0.000000,2.000000,0.000000,60.0,11.0,2.000000
50%,2.021111e+07,120000.000000,0.0,120000.000000,120000.000000,2.000000,7.000000,3.000000,61.000000,0.000000,6.000000,1.000000,60.0,11.0,8.000000
75%,2.021111e+07,175700.000000,0.0,175800.000000,175700.000000,3.000000,16.000000,6.000000,64.000000,0.000000,13.000000,2.000000,60.0,11.0,10.000000
max,2.021111e+07,235900.000000,0.0,235900.000000,235900.000000,4.000000,51.000000,99.000000,143.000000,17.000000,37.000000,23.000000,60.0,11.0,10.000000

In [ ]:
time = df['time']
hours = df['time'].dt.hour + df['time'].dt.minute/60 + df['time'].dt.second/3600